apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-sxwj
  namespace: test
  labels:
    k8s-app: elasticsearch-sxwj
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch-sxwj
  labels:
    k8s-app: elasticsearch-sxwj
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test
  name: elasticsearch-sxwj
  labels:
    k8s-app: elasticsearch-sxwj
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: elasticsearch-sxwj
  namespace: test
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: elasticsearch-sxwj
  apiGroup: ""
---
# Elasticsearch deployment itself
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: elasticsearch-sxwj
  namespace: test
  labels:
    k8s-app: elasticsearch-sxwj
    version: v6.3.2
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  serviceName: elasticsearch-sxwj
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch-sxwj
      version: v6.3.2
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-sxwj
        version: v6.3.2
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: elasticsearch-sxwj
      containers:
      #- image: gcr.io/google-containers/elasticsearch:6.3.2
      - image: 192.168.2.121/qgsoft/elasticsearch:6.3.2
        name: elasticsearch-sxwj
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-sxwj
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "cluster.name"
              value: "elasticsearch-sxwj"
        - name: "bootstrap.memory_lock"
              value: "true"
        - name: "ES_JAVA_OPTS"
              value: "-Xms8192m -Xmx8192m"
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: 192.168.2.121/qgsoft/alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-sxwj-init
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-sxwj
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "test"
      resources:
        requests:
          storage: 40Gi
