apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-sxwj
  namespace: test
  labels:
    k8s-app: elasticsearch-sxwj
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
#  clusterIP: None
  type: NodePort
  selector:
    k8s-app: elasticsearch-sxwj
